name: Tag

on:
  push:
    branches: '*'

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Package
      run: |
        cd Source
        dotnet pack --configuration Release --output .
    - name: Setup tagging
      run: |
        cd Source
        echo "FILENAME=$(ls *.nupkg | cut -d "." -f 1-5)" >> $GITHUB_ENV

    - name: Testing variables
      run: |
        echo ${{ env.FILENAME }}
    - name: Create Tag
      uses: actions/github-script@v7
      with: 
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner, 
            repo: context.repo.repo, 
            ref: 'refs/tags/${{env.FILENAME}}', 
            sha: context.sha
          })
