name: Tag

on:
  push:
    branches: '*'

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # - name: Test
    #   run: |
    #     cd Test
    #     dotnet test
    - name: Package
      run: |
        cd Source
        dotnet pack --configuration Release --output .
    - name: Tag
      run: |
        cd Source
        echo "FILENAME=$(*.nupkg)" >> $GITHUB_ENV
        echo ("$FILENAME" | ${FILE%.*})
